server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /config.js {
        add_header Cache-Control "no-store";
    }

    #location /identity-api/ {
    #   proxy_pass http://identity:8080/;
    #}

    #location /aggregator-api/ {
    #   proxy_pass http://aggregator:8080/;
    #}
}