services:
  frontend:
    build: ../../frontend
    ports:
      - "2000:80"
    environment:
      IDENTITY_URL: ${IDENTITY_URL:-}
      AGGREGATOR_URL: ${AGGREGATOR_URL:-}
    depends_on:
      - aggregator
      - identity
    restart: unless-stopped

  aggregator:
    build: ../../sims-aggregator
    environment:
      OTEL_SERVICE_NAME: ${AGGR_OTEL_SERVICE_NAME:-}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${AGGR_OTEL_EXPORTER_OTLP_ENDPOINT:-}
    depends_on:
      dbAggregator:
        condition: service_healthy
    restart: unless-stopped
    expose:
      - "3033"

  identity:
    build: ../../sims-identity
    depends_on:
      dbidentity:
        condition: service_healthy
    restart: unless-stopped

  sims-stix-ingest:
    image: ../../sims-stix-ingest
    ports:
      - "8080:8080"
    environment:
      - MongoDbSettings__ConnectionString=mongodb://${STIX_MONGO_USER}:${STIX_MONGO_PASSWORD}@dbstix:27017/?authSource=admin
    depends_on:
      dbstix:
        condition: service_healthy
    restart: unless-stopped

  dbidentity:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${ID_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ID_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ID_POSTGRES_DB}
    volumes:
      - ./dbidentity_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  
  dbAggregator:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${AGGR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AGGR_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AGGR_POSTGRES_DB}
    volumes:
      - ./dbAggregator_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  dbstix:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${STIX_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${STIX_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${STIX_MONGO_DB}
    volumes:
      - ./dbstix_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
