services:
  frontend:
    build: ../../frontend
    ports:
      - "2000:80"
    environment:
      IDENTITY_URL: ${IDENTITY_URL:-}
      AGGREGATOR_URL: ${AGGREGATOR_URL:-}
    depends_on:
      - aggregator
      - identity
    restart: unless-stopped

  aggregator:
    build: ../../sims-aggregator
    depends_on:
      dbAggregator:
        condition: service_healthy
    restart: unless-stopped
    expose:
      - "3033"

  identity:
    build: ../../sims-identity
    depends_on:
      dbidentity:
        condition: service_healthy
    restart: unless-stopped

  dbidentity:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${ID_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ID_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ID_POSTGRES_DB}
    volumes:
      - ./dbidentity_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  dbAggregator:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${AGGR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AGGR_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AGGR_POSTGRES_DB}
    volumes:
      - ./dbAggregator_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

